# Surface/graph encoders
diffusion_net:
  _target_: diffusion_net.DiffusionNetBlock
  C_width: ${model_hdim}
  dropout: ${model_dropout}
  use_bn: ${eval:'not ${use_layernorm}'}
  use_layernorm: ${use_layernorm}
  init_time: ${diff_time_mean}  # either null (for constant init) or a float
  init_std: ${diff_time_std}

gcn_block:
  _target_: atomsurf.network_utils.GCNx2Block
  dim_in: ${model_hdim}
  dim_out: ${model_hdim}
  hidden_dims: ${model_hdim}
  dropout: ${model_dropout}
  use_bn: true
  use_weighted_edge_distance: false

pronet_block:
  _target_: atomsurf.network_utils.ProNet
  level: allatom
  num_blocks: 4
  hidden_channels: ${model_hdim}
  mid_emb: ${eval:'${model_hdim} // 2'}
  num_radial: 6
  num_spherical: 2
  cutoff: 10.0
  max_num_neighbors: 32
  int_emb_layers: 3
  num_pos_emb: 16
  dropout: 0.1
  data_augment_eachlayer: False
  euler_noise: False
  add_seq_emb: False

# Message passing schemes
gat_comm:
  _target_: atomsurf.network_utils.communication.surface_graph_comm.SurfaceGraphCommunication
  s_pre_block: ${linear_halver}
  g_pre_block: ${linear_halver}
  bp_sg_block: ${gat_mp}
  bp_gs_block: ${gat_mp}
  s_post_block: ${cat_post_proc}
  g_post_block: ${cat_post_proc}
  neigh_thresh: 8
  sigma: 2.5

gvp_comm:
  _target_: atomsurf.network_utils.communication.surface_graph_comm.SurfaceGraphCommunication
  s_pre_block: ${linear_halver}
  g_pre_block: ${linear_halver}
  bp_sg_block: ${gvp_mp}
  bp_gs_block: ${gvp_mp}
  s_post_block: ${cat_post_proc}
  g_post_block: ${cat_post_proc}
  neigh_thresh: 8
  sigma: 2.5

bihmr_comm:
  _target_: atomsurf.network_utils.communication.surface_graph_comm.SurfaceGraphCommunication
  s_pre_block: ${linear_halver}
  g_pre_block: ${linear_halver}
  bp_sg_block: ${hmr_mp}
  bp_gs_block: ${hmr_mp}
  s_post_block: ${cat_post_proc}
  g_post_block: ${cat_post_proc}
  neigh_thresh: 8
  sigma: 2.5

# Protein Encoder blocks
diff|gcn|gat:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${gcn_block}
  message_passing: ${gat_comm}

gvp:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${gcn_block}
  message_passing: ${gvp_comm}

pronet|gvp:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${pronet_block}
  message_passing: ${gvp_comm}

pronet|HMRMP:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${pronet_block}
  message_passing: ${bihmr_comm}

dmasif_block:
  _target_: atomsurf.network_utils.misc_arch.dmasif_encoder.dMasifWrapper
  dim_in: ${model_hdim}
  dim_out: ${model_hdim}
  argdir: ${dmasif_config}

diffonly:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: None
  message_passing: None

dmasifonly:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${dmasif_block}
  graph_encoder: None
  message_passing: None

pronetonly:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: None
  graph_encoder: ${pronet_block}
  message_passing: None

dmasif|pronet|gvp:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${dmasif_block}
  graph_encoder: ${pronet_block}
  message_passing: ${gvp_comm}

dmasif|pronet|gvp_normals:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${dmasif_block}
  graph_encoder: ${pronet_block}
  message_passing:
    _target_: atomsurf.network_utils.ConcurrentCommunication
    use_bp: true
    pre_s_block: linear
    pre_g_block: linear
    pre_s_dim_in: ${model_hdim}
    pre_s_dim_out: ${eval:'${model_hdim} // 2'}
    pre_g_dim_in: ${model_hdim}
    pre_g_dim_out: ${eval:'${model_hdim} // 2'}
    use_gvp: true
    use_normals: true
    vector_gate: ${gvp_vector_gate}
    n_layers: ${gvp_n_layers}
    gvp_use_angles: ${gvp_use_angles}
    bp_s_dim_in: ${eval:'${model_hdim} // 2'}
    bp_s_dim_out: ${eval:'${model_hdim} // 2'}
    bp_g_dim_in: ${eval:'${model_hdim} // 2'}
    bp_g_dim_out: ${eval:'${model_hdim} // 2'}
    post_s_block: cat_post_process
    post_g_block: cat_post_process
    post_s_dim_in: ${model_hdim}
    post_s_dim_out: ${model_hdim}
    post_g_dim_in: ${model_hdim}
    post_g_dim_out: ${model_hdim}
    neigh_thresh: 8
    sigma: 2.5

